version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shopee_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopee
      MYSQL_USER: shopee
      MYSQL_PASSWORD: shopee
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:
    driver: local

